version: 0.0
os: linux
files:
  - source: .
    destination: /home/ubuntu/app
hooks:
  ApplicationStart:
    - location: scripts/install-app.sh
      runas: ubuntu
  AfterInstall:
    - location: scripts/application-start.sh
      runas: ubuntu